Add macro `_DEFAULT_SOURCE`
Glibc>2.19 deprecated `_BSD_SOURCE` for `_DEFAULT_SOURCE`:

For compatibility both macro as required as explain by `man feature_test_macros`:

_BSD_SOURCE (deprecated since glibc 2.20)
        Defining this macro with any value causes header files to expose BSD-derived definitions.

        In glibc versions up to and including 2.18, defining this macro also causes BSD definitions to be preferred in some sit‐
        uations where standards conflict, unless one or more of  _SVID_SOURCE,  _POSIX_SOURCE,  _POSIX_C_SOURCE,  _XOPEN_SOURCE,
        _XOPEN_SOURCE_EXTENDED,  or  _GNU_SOURCE  is  defined,  in which case BSD definitions are disfavored.  Since glibc 2.19,
        _BSD_SOURCE no longer causes BSD definitions to be preferred in case of conflicts.

        Since glibc 2.20, this macro is deprecated.  It now has the same effect as defining  _DEFAULT_SOURCE,  but  generates  a
        compile-time  warning  (unless  _DEFAULT_SOURCE  is  also  defined).   Use  _DEFAULT_SOURCE instead.  To allow code that
        requires _BSD_SOURCE in glibc 2.19 and earlier and _DEFAULT_SOURCE in glibc 2.20 and later to compile without  warnings,
        define both _BSD_SOURCE and _DEFAULT_SOURCE.

This fixes the following:

cc -O3 -g -pthread -D_XOPEN_SOURCE=500   -Wall -Wextra -Werror -Winit-self -std=c99 -pedantic -fPIC -Wformat -Werror=format-security -D_BSD_SOURCE  -fstack-protector-strong  -Isrc  -M src/mqlog.c | \
sed 's,\(mqlog\.o\) *:,src/\1 src/mqlog.d: ,' > src/mqlog.d.tmp
mv -f src/mqlog.d.tmp src/mqlog.d
cc -O3 -g -pthread -D_XOPEN_SOURCE=500   -Wall -Wextra -Werror -Winit-self -std=c99 -pedantic -fPIC -Wformat -Werror=format-security -D_BSD_SOURCE  -fstack-protector-strong  -Isrc   -c -o src/crc32.o src/crc32.c
In file included from /usr/include/stdlib.h:24:0,
                 from src/crc32.c:43:
/usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^~~~~~~
cc1: all warnings being treated as errors
<builtin>: recipe for target 'src/crc32.o' failed
make: *** [src/crc32.o] Error 1